from collections.abc import AsyncIterator
from typing import Protocol

from aegismcp.protocol.codec import RawMessage


class Transport(Protocol):
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    def receive(self) -> AsyncIterator[RawMessage]: ...
    async def send(self, message: RawMessage) -> None: ...
